### ISSUE TITLE
Allow local copies and aliases for un-published schemas

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Reference-Checker#1]
In order to validate references to online repositories (e.g. the DMTF's Redfish repository), the schemas must be published/available in order for the URI references to resolve.  But this creates a catch-22 if you're attempting to validate a set of schema files before publication.

Allow an alias file to re-direct certain URIs to another location, or most likely, a local copy.

**Comment by mraineri** [comment]
Fixed with PR #2
