### ISSUE TITLE
Incorrect parsed rootHost cause many failures when checking an url like https://10.10.10.10/redfish/v1/metadata/ServiceRoot_v1.xml

### ISSUE THREAD

**Issue by panyy3** [DMTF/Redfish-Reference-Checker#15]
When I run this tool to test an url, many failures are shown for incorrect parsed rootHost redfish.
Correct rootHost should be https://10.10.10.10, but rootHost is mis-recoganized as https://redfish

Running result:
# python3 RedfishReferenceTool.py https://10.10.10.10/redfish/v1/metadata/ServiceRoot_v1.xml --nochkcert
Redfish Reference Checker 1.0.0
https:/
https://10.10.10.10/redfish/v1/metadata/ServiceRoot_v1.xml
http://docs.oasis-open.org/odata/odata/v4.0/errata03/csd01/complete/vocabularies/Org.OData.Core.V1.xml
http://docs.oasis-open.org/odata/odata/v4.0/errata03/csd01/complete/vocabularies/Org.OData.Capabilities.V1.xml
/redfish/v1/metadata/Resource_v1.xml
Something went wrong: HTTPSConnectionPool(host='redfish', port=443): Max retries exceeded with url: /v1/metadata/Resource_v1.xml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd547f99cc0>: Failed to establish a new connection: [Errno 111] Connection refused',)) 
False None 
Something is wrong: No Valid Schema Found #36
......

I have tried to change L153 in "RedfishReferenceTool.py" script as below, finally it works.
Before modification:
rootHost = rootURL.rsplit('/', rootURL.count('/') - 1)[0]
After modification:
rootHost = rootURL.rsplit('/', rootURL.count('/') - 2)[0]

Running result after modification:
# python3 RedfishReferenceTool.py https://10.10.10.10/redfish/v1/metadata/ServiceRoot_v1.xml --nochkcert
Redfish Reference Checker 1.0.0
https://10.10.10.10
https://10.10.10.10/redfish/v1/metadata/ServiceRoot_v1.xml
http://docs.oasis-open.org/odata/odata/v4.0/errata03/csd01/complete/vocabularies/Org.OData.Core.V1.xml
http://docs.oasis-open.org/odata/odata/v4.0/errata03/csd01/complete/vocabularies/Org.OData.Capabilities.V1.xml
/redfish/v1/metadata/Resource_v1.xml
/redfish/v1/metadata/RedfishExtensions_v1.xml
......

Can you help to check it? Thanks.

**Comment by billdodd** [comment]
@panyy3 - thanks for reporting this issue.

Yes, the line you point out is in error and the correction you made is correct. I will fix that as well as clean up some other reporting issues I found when testing this.
