### ISSUE TITLE
Log about verification results

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Reference-Checker#18]
Hi,
Is there any opportunity for this verification tool to add the function of generating a results report? For example results.json or html file.

Thanks,
Felix

**Comment by mraineri** [comment]
Given the scope of this tool is strictly for checking publication schemas, we have no plans to expand it for more general usage.

**Comment by mraineri** [comment]
Closing; the request is out of scope for this tool's intended usage
