### ISSUE TITLE
Disable insecure warning when explicit --nochkcert option given

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfish-Reference-Checker#3]
For the case of running against a system that uses a self-signed cert, several tools have an option (like `--nochkcert`) to disable the certificate validation. But when you use that option, you will see the following warning displayed:

`InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.`

If you've explicitly used the `--nochkcert` option, the warning is just an annoyance. Suggest we disable that warning during arg processing if `--nochkcert` is specified. 

Code to do this:

```
import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning

    ...
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
    ...
```

Applies to some other tools as well, including Redfish-Service-Validator, Redfish-Interop-Validator and Redfish-Usecase-Checkers/one_time_boot.

Idea came from Paul Vancil who did this in Redfish tool.

**Comment by tomasg2012** [comment]
Yeah, I've noticed this but it happens differently on certain versions of requests or python, it seems when I see this on a more recent library, it repeats it constantly, which produces a lot of log spam.  On the version I'm developing with, it only prints once...

Thanks for the code, I saw a similar question online but with a lot of odd dispute that I never returned to reading about.

**Comment by mraineri** [comment]
Fixed in latest PR
