### ISSUE TITLE
Need local file check option

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Reference-Checker#5]
As one of the primary uses of the Checker is to ensure links are valid before publication, the tool needs an option to check local file(s) in addition to URL sources.

**Comment by tomasg2012** [comment]
Local as in located on your harddrive?  The alias has this covered, but it does not catch missing file exceptions...

**Comment by jautor** [comment]
@tomasg2012 The alias feature works for references within the files, but I didn't see a way to "check" a local file (instead of a URL).  We're trying to check a group of files before posting / releasing them.

**Comment by tomasg2012** [comment]
Ah of course.  A work around would be to write an alias for that file and just point the tool to the alias as the first target, but it'd be easier to do a cmd line option.  Should this also use asterisks?  You wouldn't be able to do asterisks on URLs but local files should work.

**Comment by jautor** [comment]
I think we can handle the wildcard on input files to simple batch commands.
For the alias function a separate alias object would be easy for "folders" instead of individual files - easy to re-use, too.

**Comment by mraineri** [comment]
Fixed in latest PR
