### ISSUE TITLE
Add directory-level aliasing 

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Reference-Checker#6]
For performing pre-release checks, the references included in the files are likely to reference numerous files (which may also be un-published).  Add a directory-level wildcard or other solution to providing an alias to an entire repository.  Creating an alias file for 80+ files is an unnecessary burden on the user.

**Comment by tomasg2012** [comment]
Oh definitely, I'll look into a solution for this, haven't worked with wildcards but using the file glob library in Python should work just fine.

**Comment by mraineri** [comment]
Fixed in latest PR
