### ISSUE TITLE
unable to parse $metdata and check all referenced schemas

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Reference-Checker#8]
When I run the tool against a $metadata URI, I get the following error:

PS C:\DevTools> python .\RedfishReferenceTool.py https://10.243.12.46/redfish/v1/$metadata --nochkcert
https://10.243.12.46
https://10.243.12.46/redfish/v1/
No Schema Found for given destination

The $metadata file is a valid XML metadata and has many Reference sections like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
    <edmx:Reference Uri="/redfish/v1/metadata/ServiceRoot_v1.xml">
        <edmx:Include Namespace="ServiceRoot" />
        <edmx:Include Namespace="ServiceRoot.v1_1_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="/redfish/v1/metadata/AccountService_v1.xml">
        <edmx:Include Namespace="AccountService" />
        <edmx:Include Namespace="AccountService.v1_0_2"/>
    </edmx:Reference>
....
    <edmx:DataServices>
        <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Service">
            <EntityContainer Name="Service" Extends="ServiceRoot.v1_1_1.ServiceContainer"/>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>

```

**Comment by samerhaj** [comment]
The same file works when used locally (as an --alias).

The Response Headers of the file indicate that it's content-type is "application/xml", which is what the code is looking for. But it is also content-encoding "gzip". is this a problem?

allow →HEAD, GET
content-encoding →gzip
content-type →application/xml
etag →W/"25fd7d3bc5231bee38a98678b3e69ee2"
odata-version →4.0
transfer-encoding →chunked

**Comment by tomasg2012** [comment]
Hmm.  What system are you running on?  The message says it was able to get "/redfish/v1", but that is not an xml.  If it is a linux machine, you will need to escape the $ character as "\\$".  If you did, then this seems to be another issue.  I believe the request library is capable of extracting gzip automatically, I'm sure.

**Comment by samerhaj** [comment]
Thanks for the tip! I was running in PowerShell, and forgot to include the URL (with the $) in single quotes.

This worked:

python RedfishReferenceTool.py 'https://10.243.12.46/redfish/v1/$metadata' --nochkcert

Closing the issue..
